-- ============================================================================
-- SCHEMA SUPABASE — Bellezza Studio (centri estetici)
-- Esegui nell'SQL Editor del progetto Supabase. Adattato dal sito barbieri:
-- "barbiere" → "operatrice", aggiunte tabelle feedback e settings allineate
-- a config.js → recensioniAuto.
-- ============================================================================

-- ── PRENOTAZIONI ───────────────────────────────────────────────────────────
create table if not exists prenotazioni (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz default now(),
  nome              text not null,
  email             text not null,
  telefono          text,
  note              text,
  consenso          boolean default false,        -- GDPR: consenso a contatto/recensione
  servizio          text not null,                -- nome del trattamento
  prezzo            numeric,
  durata            text,
  operatrice        text not null,                -- estetista scelta
  data              date not null,
  orario            text not null,
  stato             text default 'in_attesa',     -- in_attesa | confermata | cancellata
  cancel_token      uuid,
  recensione_inviata boolean default false        -- usato dall'edge function
);
create index if not exists idx_pren_data on prenotazioni(data, operatrice);
create index if not exists idx_pren_token on prenotazioni(cancel_token);

-- ── BLOCCHI (slot/giorni chiusi manualmente dal centro) ──────────────────────
create table if not exists blocchi (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now(),
  data        date not null,
  orario      text not null,                      -- orario specifico, oppure 'GIORNO' per tutta la giornata
  operatrice  text not null
);
create index if not exists idx_blocchi_data on blocchi(data, operatrice);

-- ── ANNUNCI (avviso in tempo reale a tutte le clienti sul sito) ──────────────
create table if not exists annunci (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now(),
  testo       text not null,
  attivo      boolean default true
);

-- ── FEEDBACK PRIVATI (smart routing: voti sotto soglia) ──────────────────────
create table if not exists feedback (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz default now(),
  prenotazione_id  bigint references prenotazioni(id) on delete set null,
  testo            text not null,
  contatto         text                            -- email/telefono opzionale lasciato dalla cliente
);

-- ── SETTINGS (parametri operativi letti dall'edge function recensioni) ───────
create table if not exists settings (
  key    text primary key,
  value  text
);
insert into settings (key, value) values
  ('nome_attivita',   'Bellezza Studio'),
  ('email_mittente',  'Bellezza Studio <onboarding@resend.dev>'),
  ('google_place_id', 'YOUR_GOOGLE_PLACE_ID'),
  ('ore_attesa',      '3'),
  ('soglia_stelle',   '4'),
  ('msg_richiesta',   'Com''è andato il tuo {trattamento}? Ci basta un attimo del tuo tempo 💖')
on conflict (key) do nothing;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
alter table prenotazioni enable row level security;
alter table blocchi      enable row level security;
alter table annunci      enable row level security;
alter table feedback     enable row level security;

-- Le clienti (anon) possono: creare una prenotazione, leggere SOLO gli orari
-- occupati (per la disponibilità), inviare un feedback, leggere annunci/blocchi.
create policy "anon insert prenotazioni" on prenotazioni for insert to anon with check (true);
create policy "anon read orari"          on prenotazioni for select to anon using (true);
-- NB: per non esporre i dati personali, in produzione crea una VIEW che mostra
-- solo (data, orario, operatrice, stato) e dai il select su quella, non sulla tabella.

create policy "anon read blocchi"  on blocchi  for select to anon using (true);
create policy "anon read annunci"  on annunci  for select to anon using (attivo = true);
create policy "anon insert feedback" on feedback for insert to anon with check (true);

-- Gli admin autenticati hanno accesso completo (gestione dal pannello/dashboard).
create policy "auth all prenotazioni" on prenotazioni for all to authenticated using (true) with check (true);
create policy "auth all blocchi"      on blocchi      for all to authenticated using (true) with check (true);
create policy "auth all annunci"      on annunci      for all to authenticated using (true) with check (true);
create policy "auth all feedback"     on feedback     for all to authenticated using (true) with check (true);

-- Realtime per disponibilità e annunci in tempo reale
alter publication supabase_realtime add table prenotazioni;
alter publication supabase_realtime add table blocchi;
alter publication supabase_realtime add table annunci;
